use_frameworks!

platform :ios, '10.0'

target 'CFPagingEnableLayout_Example' do
  pod 'CFPagingEnableLayout', :path => '../'

  target 'CFPagingEnableLayout_Tests' do
    inherit! :search_paths

    
  end
end
